main: com.winthier.title.TitlePlugin
name: Title

version: 0.1
api-version: '1.21.10'

description: Manage custom player titles
author: StarTux
website: https://cavetale.com

depend: [Core, SQL, Mytems]
softdepend: []

commands:

  title:
    description: Select your in-game title
    usage: |-
      §b/title§8 - §7List your available titles
      §b/title <title>§8 - §7Set your title
    permission: title.title

  titles:
    description: Titles admin interface
    permission: title.admin
    usage: /titles

  gradient:
    description: Make a gradient
    permission: title.gradient
    usage: |-
      USAGE
        /gradient OPTIONS TITLE
      OPTIONS
        -c COLORS Define color gradient
        -i italic
        -b bold
        -u underlined
        -d debug
      COLORS
        Comma separated list of hex colors
        Hex color: RRGGBB
        Colors example: 808080,FF00FF,00000FF
      EXAMPLE
        /gradient -c 000000,FFFFFF -- Hello World

  shine:
    description: Use your shine
    usage: /shine
    permission: title.shine

  badge:
    description: Select a badge
    usage: /badge
    permission: title.badge

permissions:

  title.title:
    description: Use the "/title" command
    default: op

  title.admin:
    description: Use admin commands
    default: op

  title.shine:
    description: Use your shine
    default: op

  title.badge:
    description: Select a badge
    default: op