name: Title
description: Manage custom player titles
author: StarTux
version: 0.1
main: com.winthier.title.TitlePlugin
depend: [ SQL, PlayerCache ]
softdepend: [ Vault ]
commands:
  title:
    description: Select your in-game title
    usage: |-
      /<command> - List your available titles
      /<command> <title> - Set your title
    permission: title.title
  titles:
    description: Titles admin interface
    usage: |-
      /<command> list - List all titles
      /<command> list <player> - List titles of a player
      /<command> listplayers <player> - List players who own a title
      /<command> ranktitles <player> - Rank titles by ownership
      /<command> unlock <player> <title> - Unlock a title for a player
      /<command> lock <player> <title> - Lock a title for a player
      /<command> create <name> <title> - Create or update a title
      /<command> desc <name> <title> - Set description for a title
      /<command> set <player> <title> - Set a title for a player
      /<command> unlockset <player> - Unlock and set title for a player
      /<command> reset <player> - Reset the title of a player
    permission: title.admin
permissions:
  title.title:
    description: Use the "/title" command
    default: op
  title.admin:
    description: Use admin commands
    default: op
