name: Title
description: Manage custom player titles
author: StarTux
version: 0.1
api-version: 1.13
website: https://cavetale.com
main: com.winthier.title.TitlePlugin
depend: [ SQL, PlayerCache ]
softdepend: []
commands:
  title:
    description: Select your in-game title
    usage: |-
      /title - List your available titles
      /title <title> - Set your title
    permission: title.title
  titles:
    description: Titles admin interface
    usage: |-
      §e /titles list§8 - §7List all titles
      §e /titles list <player>§8 - §7List titles of a player
      §e /titles info <title>§8 - §7Print title info
      §e /titles listplayers <title>§8 - §7List players who own a title
      §e /titles ranktitles§8 - §7Rank titles by ownership
      §e /titles has <player> <title>§8 - §7Check if player has title
      §e /titles unlock <player> <title>§8 - §7Unlock a title for a player
      §e /titles lock <player> <title>§8 - §7Lock a title for a player
      §e /titles create <name> <title>§8 - §7Create or update a title
      §e /titles desc <name>§8 - §7View title description
      §e /titles desc <name> <title>§8 - §7Set description for a title
      §e /titles set <player> <title>§8 - §7Set a title for a player
      §e /titles unlockset <player> <title...>§8 - §7Unlock and set title for a player. The first unowned title will be picked, the rest ignored.
      §e /titles search <term>§8 - §7Search for matching title or description
      §e /titles reset <player>§8 - §7Reset the title of a player
      §e /titles reload§8 - §7Reload database
    permission: title.admin
permissions:
  title.title:
    description: Use the "/title" command
    default: op
  title.admin:
    description: Use admin commands
    default: op
