name: Title
description: Manage custom player titles
author: StarTux
version: 0.1
api-version: 1.13
website: https://cavetale.com
main: com.winthier.title.TitlePlugin
depend: [ SQL, PlayerCache ]
softdepend: []
commands:
  title:
    description: Select your in-game title
    usage: |-
      /title - List your available titles
      /title <title> - Set your title
    permission: title.title
  titles:
    description: Titles admin interface
    usage: |-
      /titles list - List all titles
      /titles list <player> - List titles of a player
      /titles listplayers <player> - List players who own a title
      /titles ranktitles <player> - Rank titles by ownership
      /titles has <player> <title> - Check if player has title
      /titles unlock <player> <title> - Unlock a title for a player
      /titles lock <player> <title> - Lock a title for a player
      /titles create <name> <title> - Create or update a title
      /titles desc <name> - View title description
      /titles desc <name> <title> - Set description for a title
      /titles set <player> <title> - Set a title for a player
      /titles unlockset <player> - Unlock and set title for a player
      /titles reset <player> - Reset the title of a player
      /titles reload - Reload database
    permission: title.admin
permissions:
  title.title:
    description: Use the "/title" command
    default: op
  title.admin:
    description: Use admin commands
    default: op
